### ISSUE TITLE
Could you publish the latest version?

### ISSUE THREAD

**Issue by augustocdias** [nlopes/actix-web-prom#10]
Could you publish the latest version with the latest version of the prometheus rust library to crates.io?

**Comment by nlopes** [comment]
Will do. I've been quite swamped and haven't been paying attention here too much. Things should get sorted soon. Thanks for the patience.

**Comment by nlopes** [comment]
Done. Apologies for the fact that it has a breaking change (check the custom labels commit) but as I'm still on 0.Y.Z releases, I think that's acceptable per semver. Once I hit 1.Y.Z, these won't occur anymore.
