### ISSUE TITLE
Wrong response times

### ISSUE THREAD

**Issue by JanPel** [nlopes/actix-web-prom#13]
Currently the timing of the reponse times seems off. I think because on line 355 and 356:
 `           fut: self.service.call(req),  
            clock: SystemTime::now(),`
Is in the wrong order, so the processing of the request is started before the timer is initiated. 
Should be fixed by initiating the time before making the MetricsResponse object. If needed I am happy to make a pull request for this.

**Comment by nlopes** [comment]
A PR would be 👌

**Comment by sd2k** [comment]
FWIW I recently switched rocket_prometheus to use [`Instant::now()`](https://doc.rust-lang.org/std/time/struct.Instant.html) instead of [`SystemTime::now()`](https://doc.rust-lang.org/std/time/struct.SystemTime.html) so it might be worth making the same change here :slightly_smiling_face:

**Comment by JanPel** [comment]
Okay done! Also changed SystemTIme to Instant.
