### ISSUE TITLE
0.2.0 Crate Release

### ISSUE THREAD

**Issue by tomsanbear** [nlopes/actix-web-prom#18]
Great work, just one thing, when fetching from crates.io the latest version available is 0.1.4 version. Could you bump the version and release on crates? I don't mind drafting a PR for github action/travis/etc... config to automate this process in the future. LMK your thoughts.

**Comment by nlopes** [comment]
Apologies for never coming back to this. 0.2.0 should be out for sometime now.

**Comment by tyranron** [comment]
@nlopes would you be so kind to release current master on crates.io? LAtest release has conflicts with prometheus 0.9.
