### ISSUE TITLE
actix 3 release bump

### ISSUE THREAD

**Issue by clux** [nlopes/actix-web-prom#32]
Thanks for this crate! This is probably a simple one :-)

[actix 3 was just released](https://paper.dropbox.com/published/Announcing-Actix-Web-v3.0--A7YI~P9U9aqhEOXyZJaGffjfBg-QOXXb1lXgTubzXHzUq9ONY5), and it probably requires a bump of actix herein, as I'm seeing this when upgrading:

```
error[E0271]: type mismatch resolving `<actix_web_prom::PrometheusMetrics as actix_web::dev::Transform<<impl actix_service::ServiceFactory as actix_service::ServiceFactory>::Service>>::Request == actix_web::dev::ServiceRequest`
   --> version.rs:100:14
    |
100 |             .wrap(prometheus.clone())
    |              ^^^^ expected struct `actix_web::service::ServiceRequest`, found struct `actix_web::dev::ServiceRequest`
    |
    = note: perhaps two different versions of crate `actix_web` are being used?
```

**Comment by nlopes** [comment]
Which version of the crate are you using? `0.5.0` should have actix-web at version 3 and actix-service at 1.0.6.

If you're not on `0.5.0`, please upgrade to `0.5.0`.

**Comment by clux** [comment]
Ah, 0.5.0 wasn't out when I tested. That version works. Thank you!

**Comment by nlopes** [comment]
Thanks for raising, truly appreciate it!
