### ISSUE TITLE
no default features for actix-web

### ISSUE THREAD

**Issue by robjtede** [nlopes/actix-web-prom#35]
The dependency in Cargo.toml should ideally be:

```diff
- actix-web = "3.0.2"
+ actix-web = { version = "3.0.2", default-features = false }
```

**Comment by nlopes** [comment]
Thanks for the suggestion!

**Comment by nlopes** [comment]
Sorted in https://github.com/nlopes/actix-web-prom/commit/5e874001862842226cf4dfedd6249ef193079e97
