### ISSUE TITLE
Provide a way to use actix-web-prom with actix-web 4.0.0

### ISSUE THREAD

**Issue by arthurlm** [nlopes/actix-web-prom#51]
Hi,

There currently multiple PRs pending to allow usage of `actix-web-prom` with `actix-web = "4.0.0"` (see: https://github.com/nlopes/actix-web-prom/pull/45, https://github.com/nlopes/actix-web-prom/pull/44).

I have read discussions and seen that maintainers do not want to have `beta` version in `master` branch.
This is perfectly understandable. Indeed, libraries releases should __never__ depends on beta versions.

However, it would be awesome if you could provide a branch allowing users to continue using `actix-web-prom` with new versions of `actix-web`.

I have done this in my fork (see [changes](https://github.com/nlopes/actix-web-prom/compare/master...arthurlm:actix-next)) and it works out of the box changing `Cargo.toml` like bellow:

```diff
- actix-web-prom = "0.5"
+ actix-web-prom = { git = "https://github.com/arthurlm/actix-web-prom.git", branch = "actix-next" }
```

Would you like me to create a PR on branch `actix-next` in your repository (and not merging into `master`) ?

Do you have any better ideas to allow users continue using your works with `actix-web = "4.0.0-beta.X"` ?

**Comment by nlopes** [comment]
Fairly happy to do so if you'd be so kind as to set that PR.

**Comment by nlopes** [comment]
I think `actix-web` is getting fairly close to a `4.0` release so I started a PR that brings `actix-web-prom` in line with the latest beta. I'm also going to try to take the `-beta.N` approach to give the community more flexibility.

You can check my PR at https://github.com/nlopes/actix-web-prom/pull/57
