### ISSUE TITLE
Release, please

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [nlopes/actix-web-prom#77]
Hi!

Since #76 is merged, could you bump the version and release on crates?

Thanks!

**Comment by nlopes** [comment]
I'm currently thinking about releasing after I review another couple PRs - do you not have the option of using a commit sha from github for the time being? If you don't have that option I'll come back to this in a few hours and rethink it.

```
[dependencies]
actix-web-prom = { git = "https://github.com/nlopes/actix-web-prom.git", rev = "xxxxxxxx" }
```

**Comment by Alexey-N-Chernyshov** [comment]
Yes, sure

**Comment by ross-paypay** [comment]
@nlopes How about cutting a release now? 
I think there are some very useful features that have been added recently. 😄

**Comment by nlopes** [comment]
Will do, thanks for the reminder!

**Comment by Alexey-N-Chernyshov** [comment]
Thanks!
