### ISSUE TITLE
How to secure an endpoint?

### ISSUE THREAD

**Issue by DenuxPlays** [nlopes/actix-web-prom#81]
Hey,
How can I secure the metrics endpoint?
Or just but a wrapper around it?

**Comment by nlopes** [comment]
Hey @DenuxPlays I think this is outside of the scope of `actix-web-prom`. You probably want to add https to your `actix-web` deployment. Check more [here](https://actix.rs/docs/server/#tls--https).

**Comment by DenuxPlays** [comment]
> Hey @DenuxPlays I think this is outside of the scope of `actix-web-prom`. You probably want to add https to your `actix-web` deployment. Check more [here](https://actix.rs/docs/server/#tls--https).

That was not what I meant.
I meant to secure it with credentials so that the endpoint is not public.
But maybe this can be achieved with actix when I wrap a guard around it. Have to test it though.
